/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	samplecomponentv1 "github.com/blackducksoftware/synopsys-operator/pkg/api/sample-component/v1"
	versioned "github.com/blackducksoftware/synopsys-operator/pkg/sample-component/client/clientset/versioned"
	internalinterfaces "github.com/blackducksoftware/synopsys-operator/pkg/sample-component/client/informers/externalversions/internalinterfaces"
	v1 "github.com/blackducksoftware/synopsys-operator/pkg/sample-component/client/listers/sample-component/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SampleComponentInformer provides access to a shared informer and lister for
// SampleComponents.
type SampleComponentInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.SampleComponentLister
}

type sampleComponentInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSampleComponentInformer constructs a new informer for SampleComponent type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSampleComponentInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSampleComponentInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSampleComponentInformer constructs a new informer for SampleComponent type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSampleComponentInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SynopsysV1().SampleComponents(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SynopsysV1().SampleComponents(namespace).Watch(options)
			},
		},
		&samplecomponentv1.SampleComponent{},
		resyncPeriod,
		indexers,
	)
}

func (f *sampleComponentInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSampleComponentInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *sampleComponentInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&samplecomponentv1.SampleComponent{}, f.defaultInformer)
}

func (f *sampleComponentInformer) Lister() v1.SampleComponentLister {
	return v1.NewSampleComponentLister(f.Informer().GetIndexer())
}
