/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/blackducksoftware/synopsys-operator/pkg/api/sample-component/v1"
	scheme "github.com/blackducksoftware/synopsys-operator/pkg/sample-component/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SampleComponentsGetter has a method to return a SampleComponentInterface.
// A group's client should implement this interface.
type SampleComponentsGetter interface {
	SampleComponents(namespace string) SampleComponentInterface
}

// SampleComponentInterface has methods to work with SampleComponent resources.
type SampleComponentInterface interface {
	Create(*v1.SampleComponent) (*v1.SampleComponent, error)
	Update(*v1.SampleComponent) (*v1.SampleComponent, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.SampleComponent, error)
	List(opts metav1.ListOptions) (*v1.SampleComponentList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.SampleComponent, err error)
	SampleComponentExpansion
}

// sampleComponents implements SampleComponentInterface
type sampleComponents struct {
	client rest.Interface
	ns     string
}

// newSampleComponents returns a SampleComponents
func newSampleComponents(c *SynopsysV1Client, namespace string) *sampleComponents {
	return &sampleComponents{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the sampleComponent, and returns the corresponding sampleComponent object, and an error if there is any.
func (c *sampleComponents) Get(name string, options metav1.GetOptions) (result *v1.SampleComponent, err error) {
	result = &v1.SampleComponent{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("samplecomponents").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SampleComponents that match those selectors.
func (c *sampleComponents) List(opts metav1.ListOptions) (result *v1.SampleComponentList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.SampleComponentList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("samplecomponents").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested sampleComponents.
func (c *sampleComponents) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("samplecomponents").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a sampleComponent and creates it.  Returns the server's representation of the sampleComponent, and an error, if there is any.
func (c *sampleComponents) Create(sampleComponent *v1.SampleComponent) (result *v1.SampleComponent, err error) {
	result = &v1.SampleComponent{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("samplecomponents").
		Body(sampleComponent).
		Do().
		Into(result)
	return
}

// Update takes the representation of a sampleComponent and updates it. Returns the server's representation of the sampleComponent, and an error, if there is any.
func (c *sampleComponents) Update(sampleComponent *v1.SampleComponent) (result *v1.SampleComponent, err error) {
	result = &v1.SampleComponent{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("samplecomponents").
		Name(sampleComponent.Name).
		Body(sampleComponent).
		Do().
		Into(result)
	return
}

// Delete takes name of the sampleComponent and deletes it. Returns an error if one occurs.
func (c *sampleComponents) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("samplecomponents").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *sampleComponents) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("samplecomponents").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched sampleComponent.
func (c *sampleComponents) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.SampleComponent, err error) {
	result = &v1.SampleComponent{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("samplecomponents").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
