/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	samplecomponentv1 "github.com/blackducksoftware/synopsys-operator/pkg/api/sample-component/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSampleComponents implements SampleComponentInterface
type FakeSampleComponents struct {
	Fake *FakeSynopsysV1
	ns   string
}

var samplecomponentsResource = schema.GroupVersionResource{Group: "synopsys", Version: "v1", Resource: "samplecomponents"}

var samplecomponentsKind = schema.GroupVersionKind{Group: "synopsys", Version: "v1", Kind: "SampleComponent"}

// Get takes name of the sampleComponent, and returns the corresponding sampleComponent object, and an error if there is any.
func (c *FakeSampleComponents) Get(name string, options v1.GetOptions) (result *samplecomponentv1.SampleComponent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(samplecomponentsResource, c.ns, name), &samplecomponentv1.SampleComponent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*samplecomponentv1.SampleComponent), err
}

// List takes label and field selectors, and returns the list of SampleComponents that match those selectors.
func (c *FakeSampleComponents) List(opts v1.ListOptions) (result *samplecomponentv1.SampleComponentList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(samplecomponentsResource, samplecomponentsKind, c.ns, opts), &samplecomponentv1.SampleComponentList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &samplecomponentv1.SampleComponentList{ListMeta: obj.(*samplecomponentv1.SampleComponentList).ListMeta}
	for _, item := range obj.(*samplecomponentv1.SampleComponentList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested sampleComponents.
func (c *FakeSampleComponents) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(samplecomponentsResource, c.ns, opts))

}

// Create takes the representation of a sampleComponent and creates it.  Returns the server's representation of the sampleComponent, and an error, if there is any.
func (c *FakeSampleComponents) Create(sampleComponent *samplecomponentv1.SampleComponent) (result *samplecomponentv1.SampleComponent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(samplecomponentsResource, c.ns, sampleComponent), &samplecomponentv1.SampleComponent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*samplecomponentv1.SampleComponent), err
}

// Update takes the representation of a sampleComponent and updates it. Returns the server's representation of the sampleComponent, and an error, if there is any.
func (c *FakeSampleComponents) Update(sampleComponent *samplecomponentv1.SampleComponent) (result *samplecomponentv1.SampleComponent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(samplecomponentsResource, c.ns, sampleComponent), &samplecomponentv1.SampleComponent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*samplecomponentv1.SampleComponent), err
}

// Delete takes name of the sampleComponent and deletes it. Returns an error if one occurs.
func (c *FakeSampleComponents) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(samplecomponentsResource, c.ns, name), &samplecomponentv1.SampleComponent{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSampleComponents) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(samplecomponentsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &samplecomponentv1.SampleComponentList{})
	return err
}

// Patch applies the patch and returns the patched sampleComponent.
func (c *FakeSampleComponents) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *samplecomponentv1.SampleComponent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(samplecomponentsResource, c.ns, name, pt, data, subresources...), &samplecomponentv1.SampleComponent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*samplecomponentv1.SampleComponent), err
}
